// The pictures in the home page's scrolling TV carousel, in order, with
// the caption shown under each one when it is opened full size (also its
// screen-reader description). Edit by hand or with the carousel caption
// editor (/carousel-editor in local development).
export const CAROUSEL_IMAGES = [
  { src: "/carousel/tree-head-cliff.jpg", alt: "I remember when I was creating this that I knew I wanted to created characters from another world but see myself in them.  A stylish dapper man that's actually a tree.  He grows strong and is stoic and one with the world." },
  { src: "/carousel/grad-cap-hallway.jpg", alt: "My first graduation, at least that I can remember.  I remember this school in and out.  I was always a nervous kid but this day both of my parents where there to see me walk so I was excited more than anything.  I also was suppose to be singing a solo." },
  { src: "/carousel/black-samurai-jungle.jpg", alt: "The first ever draft of Kenji: The last afro-Japanese samurai.  He inspired the direction of my home decor and haven when I most recently moved.  He travels exotic lands in search of mystic treasure which merely is enlightenment." },
  { src: "/carousel/ocean-horizon.jpg", alt: "I believe this is Greece" },
  { src: "/carousel/kitchen-party-portrait.jpg", alt: "Kathy Jo Spears, beautiful and coo hanging with one of my uncs" },
  { src: "/carousel/flying-men.jpg", alt: "Collabed with a friend at the time on this piece that would later launch more entries into the Nostalgia Room Collection." },
  { src: "/carousel/forest-portrait.jpg", alt: "A double-exposure portrait blended with a forest canopy" },
  { src: "/carousel/straw-hat-wedding-selfie.jpg", alt: "My sister finally got hitch ya'll.  What a time we had.  It was my pride and joy to walk her down the aisle.  We've been through so much.  I wish our Momma could've seen it." },
  { src: "/carousel/paradise-cover.jpg", alt: "Album cover artwork, \"Paradise\" by Jamal Moore featuring Kenyon Dixon.  I was immediately sold on the concept and knocked it out on the first try.  Always a pleasure when it works." },
  { src: "/carousel/jungle-toucan.jpg", alt: "Harriett Tubman - A piece I curated meant for a historical black calendar I always wanted to create." },
  { src: "/carousel/school-letter-k.jpg", alt: "Everything has a beginning.  This was the first graduation I've ever had.  Not sure what grade but it was definitely Ermel Elementary in Houston, TX.  Time has flown." },
  { src: "/carousel/beach-family-fence.jpg", alt: "Family time at the beach" },
  { src: "/carousel/photoshop-desk.jpg", alt: "This was the first draft of the shape I created to be painted on my living room wall.  I had never down such a thing but it turned out pretty spectacular if I should say so myself.  Different colors for sure. lol" },
  { src: "/carousel/cloud-flight-illustration.jpg", alt: "I always wanted to design a depiction of falling into the sky.  Another completed thought." },
  { src: "/carousel/fiddle-leaf-window.jpg", alt: "I enjoy all rainy days in Los Angeles.  Few and far between.  Very calming.  Always peaceful." },
  { src: "/carousel/three-faces.jpg", alt: "These 3 ladies showed up to this photoshoot and truly committed to creating beautiful images.  Various in shape, size, and shades.  Joshua Tree photoshoot for ASO+ASA campaign" },
  { src: "/carousel/seventeen-leaves.jpg", alt: "The day it all began.  My number; my moment.  New Life" },
  { src: "/carousel/rainy-alley-bmw.jpg", alt: "A rainy New Years Eve" },
  { src: "/carousel/night-village-illustration.jpg", alt: "Creating an Udi art series and this is the 2nd piece." },
  { src: "/carousel/floating-armchair.jpg", alt: "I was working on this it seemed like forever but I'm pleased with the photos and design.  It truly came together and depicted woman in multiple roles of life.  Swisyzina is" },
  { src: "/carousel/desert-ocean.jpg", alt: "A figure reclined between desert dunes and an ocean horizon at sunset" },
  { src: "/carousel/beach-selfie-shades.jpg", alt: "A sunlit group selfie at the beach, four faces in sunglasses and bucket hats" },
  { src: "/carousel/family-portrait-vintage.jpg", alt: "A vintage family portrait at a waterfront railing, caught mid-celebration" },
  { src: "/carousel/graduation-walk-diploma.jpg", alt: "A boy carries his diploma down the aisle at a kindergarten graduation" },
  { src: "/carousel/streetball-palms.jpg", alt: "A black-and-white photograph of a streetball court framed by palm trees" },
  { src: "/carousel/underwater-boxer.jpg", alt: "A boxer shadowboxing underwater among fish and lightning" },
  { src: "/carousel/blue-suit-mercedes.jpg", alt: "A man in a blue windowpane three-piece suit leaning against a Mercedes under a big sky" },
  { src: "/carousel/botanical-birds-illustration.jpg", alt: "An ornate illustration of tropical birds, flowers, and a traveling figure" },
  { src: "/carousel/gallery-wall-interior.jpg", alt: "An interior moment in a room lined with a gallery wall of framed photographs" },
  { src: "/carousel/bandana-sunglasses.jpg", alt: "A floating bandana and sunglasses composite with green and gold smoke" },
  { src: "/carousel/kindergarten-graduation-teacher.jpg", alt: "A kindergarten graduate flanked by his teacher and a classmate beneath the alphabet frieze" },
  { src: "/carousel/texas-cap-kitchen.jpg", alt: "A man in a Texas cap and a young boy throwing peace signs in a bright kitchen" },
  { src: "/carousel/cloud-suit-figure.jpg", alt: "A tall figure in a plaid suit and fedora standing among clouds" },
  { src: "/carousel/smoke-dissolve-portrait.jpg", alt: "A tailored figure dissolving into green smoke and leaves" },
  { src: "/carousel/kaleidoscope-24.jpg", alt: "A kaleidoscope design built from basketball motion and numerals" },
];
