// The pictures in the home page's scrolling TV carousel, in order, with
// the caption shown under each one when it is opened full size (also its
// screen-reader description). Edit by hand or with the carousel caption
// editor (/carousel-editor in local development).
export const CAROUSEL_IMAGES = [
  { src: "/carousel/tree-head-cliff.jpg", alt: "A surreal black-and-white portrait of a bonsai tree standing in for a man's head, seated on a cliff above the sea" },
  { src: "/carousel/grad-cap-hallway.jpg", alt: "A young boy in a paper graduation cap walking a school hallway, caught mid-stride" },
  { src: "/carousel/black-samurai-jungle.jpg", alt: "A figure in gold-and-black samurai armor standing sword in hand in a misty jungle" },
  { src: "/carousel/ocean-horizon.jpg", alt: "A calm ocean horizon, still water meeting a soft sky" },
  { src: "/carousel/kitchen-party-portrait.jpg", alt: "A vintage portrait of a woman seated at a kitchen counter mid-gathering" },
  { src: "/carousel/flying-men.jpg", alt: "Two figures suspended mid-fall through a surreal cloud, part of a personal design series" },
  { src: "/carousel/forest-portrait.jpg", alt: "A double-exposure portrait blended with a forest canopy" },
  { src: "/carousel/straw-hat-wedding-selfie.jpg", alt: "A close selfie of a couple on their wedding day, one in a straw hat, one in a veil" },
  { src: "/carousel/paradise-cover.jpg", alt: "Album cover artwork, \"Paradise\" by Jamal Moore featuring Kenyon Dixon" },
  { src: "/carousel/jungle-toucan.jpg", alt: "An illustrated jungle scene with toucans, flowers, and a traveler" },
  { src: "/carousel/school-letter-k.jpg", alt: "A boy in an orange paper cap beside a towering letter K on a brick school wall" },
  { src: "/carousel/beach-family-fence.jpg", alt: "A family gathered at a weathered beach fence in the summer light" },
  { src: "/carousel/photoshop-desk.jpg", alt: "A laptop open to a design in progress — abstract green and coral shapes in Photoshop" },
  { src: "/carousel/cloud-flight-illustration.jpg", alt: "A silhouetted figure tumbling through a cloud-framed sky, birds scattered around him and sunlight bursting below" },
  { src: "/carousel/fiddle-leaf-window.jpg", alt: "A fiddle-leaf fig framed against a rain-flecked window and the city beyond" },
  { src: "/carousel/three-faces.jpg", alt: "Three faces layered among tropical leaves in a green composite portrait" },
  { src: "/carousel/seventeen-leaves.jpg", alt: "The numerals 17 filled with vivid blue and green leaf photography" },
  { src: "/carousel/rainy-alley-bmw.jpg", alt: "A figure in a leather jacket walking past a rain-soaked vintage BMW in a lit alley at night" },
  { src: "/carousel/night-village-illustration.jpg", alt: "A painterly illustration of a figure in a blue coat overlooking a moonlit hillside village" },
  { src: "/carousel/floating-armchair.jpg", alt: "A woman perched on a floating leaf-covered armchair above a jungle horizon" },
  { src: "/carousel/desert-ocean.jpg", alt: "A figure reclined between desert dunes and an ocean horizon at sunset" },
  { src: "/carousel/beach-selfie-shades.jpg", alt: "A sunlit group selfie at the beach, four faces in sunglasses and bucket hats" },
  { src: "/carousel/family-portrait-vintage.jpg", alt: "A vintage family portrait at a waterfront railing, caught mid-celebration" },
  { src: "/carousel/graduation-walk-diploma.jpg", alt: "A boy carries his diploma down the aisle at a kindergarten graduation" },
  { src: "/carousel/streetball-palms.jpg", alt: "A black-and-white photograph of a streetball court framed by palm trees" },
  { src: "/carousel/underwater-boxer.jpg", alt: "A boxer shadowboxing underwater among fish and lightning" },
  { src: "/carousel/blue-suit-mercedes.jpg", alt: "A man in a blue windowpane three-piece suit leaning against a Mercedes under a big sky" },
  { src: "/carousel/botanical-birds-illustration.jpg", alt: "An ornate illustration of tropical birds, flowers, and a traveling figure" },
  { src: "/carousel/gallery-wall-interior.jpg", alt: "An interior moment in a room lined with a gallery wall of framed photographs" },
  { src: "/carousel/bandana-sunglasses.jpg", alt: "A floating bandana and sunglasses composite with green and gold smoke" },
  { src: "/carousel/kindergarten-graduation-teacher.jpg", alt: "A kindergarten graduate flanked by his teacher and a classmate beneath the alphabet frieze" },
  { src: "/carousel/texas-cap-kitchen.jpg", alt: "A man in a Texas cap and a young boy throwing peace signs in a bright kitchen" },
  { src: "/carousel/cloud-suit-figure.jpg", alt: "A tall figure in a plaid suit and fedora standing among clouds" },
  { src: "/carousel/smoke-dissolve-portrait.jpg", alt: "A tailored figure dissolving into green smoke and leaves" },
  { src: "/carousel/kaleidoscope-24.jpg", alt: "A kaleidoscope design built from basketball motion and numerals" },
];
