// Graphic design / composite work, shared by the full gallery (/design)
// and any other spot on the site that pulls from it (e.g. the portfolio
// page's commissioned-work column). Add new pieces by dropping an
// optimized image in public/design/ and adding an entry here (src + a
// caption, used as the lightbox caption and, via any #hashtags in it, as
// filter tags — #commission also draws the gold badge and is what
// selects pieces for the portfolio page's commissioned grid).
export const PIECES = [
  { src: "/design/aerial-beach-face.jpg", alt: "\"Nostalgia Room\" — #selfportrait\n#graphicdesign #photography #compositing", subtitle: "Private Beach", medium: "Photography Digital Composite, Self-Work", note: "An ecosystem orbits peace" },
  { src: "/design/apartment-selector-flyer.jpg", alt: "\"Apartment Selector\" — #graphicdesign #compositing #marketing #commission #business #photography", medium: "Photography, Digital Composite, Marketing", note: "commissioned advertising card; real estate" },
  { src: "/design/aso-asa-desert-astronaut.jpg", alt: "\"ASO+ASA\" — #commission #graphicdesign #photography #compositing #campaign #surrealism", medium: "photography, Digital Composite, Campaign", note: "commissioned ASO+ASA campaign shoot & edit ad" },
  { src: "/design/badu-butterflies-molten-sunset.jpg", alt: "\"Badu - 1\" — #badu #coverart #graphicdesign #compositing #surrealism #afroart #shortfilm", medium: "Cover, Series, Digital Composite", note: "\"Badu\" is a cover art piece commissioned for series submission" },
  { src: "/design/badu-metallic-smoke-blades.jpg", alt: "\"Badu - 2\" — #badu #coverart #graphicdesign #compositing #surrealism #commission #shortfilm", medium: "Cover, Series, Digital Composite", note: "\"Badu\" is a cover art piece commissioned for series submission" },
  { src: "/design/balloon-chair-portrait.jpg", alt: "\"Nostalgia Room\" — #photography #graphicdesign #surrealism #compositing", subtitle: "Birthday Boi", medium: "Photography, Digital Composite, Self-Work", note: "Surrealism compositing; depiction of nostalgic inner childlike minimalistic dreamscape" },
  { src: "/design/bird-head-balloon-girl.jpg", alt: "\"Nostalgia Room\" — #graphicdesign #surrealism #compositing", subtitle: "Imaginary Friend", note: "Whose the imaginary friend??" },
  { src: "/design/bobs-cookout-poster.jpg", alt: "\"Bob's Cookout\" — #posters #graphicdesign #compositing #campaign #commission #livemusic #music", medium: "Cover Art, Digital Composite", note: "Commissioned album art for draft EP project for client" },
  { src: "/design/book-lantern-reader.jpg", alt: "\"Nostalgia Room\" — #selfportrait #photography #graphicdesign #compositing", subtitle: "Book Cover", medium: "Photography, Digital Composite, Self-Work", note: "Covid-19 era, isolation meets hobby in Burbank Home" },
  { src: "/design/brick-wall-plaid-suit.jpg", alt: "\"Grey in Alley\" — #blackandwhite #photography #lightroom #portfolio #model #photocommission", note: "Editorial shoot; fashion" },
  { src: "/design/cloud-catch-duo.jpg", alt: "\"Nostalgia Room\" — #photocommission #graphicdesign #photography #surrealism #compositing", subtitle: "Dewey on the Move", note: "Commissioned surrealism piece for client request" },
  { src: "/design/clouded-suit-portrait.jpg", alt: "\"Nostalgia Room\" — #graphicdesign #compositing #aiclouds #surrealism #afroart", subtitle: "Udi on the Move", medium: "Digital Composite, Self-Work", note: "grandiose meets lifestyle; Udi Ubong muse" },
  { src: "/design/cosmic-wave-earring-woman.jpg", alt: "\"Galactic Lady\" — #commission #photography #graphicdesign #compositing #campaign #surrealism", medium: "Photography, Digital Composite, Campaign", note: "The Galatic Lady is cosmic and melonated" },
  { src: "/design/cozy-plant-room.jpg", alt: "\"Nostalgia Room\" — #selfportrait #photography #ailighting", subtitle: "Homebody", note: "A homebody moment; DTLA" },
  { src: "/design/desert-ocean-falling-man.jpg", alt: "\"Nostalgia Room\" — #commission #graphicdesign #compositing #coverart #surrealism #music", subtitle: "Nostalgia Beach", note: "Commission surrealism; album art; portal into the desert dusk on the Nostalgia Beach" },
  { src: "/design/diamond-earth-ribbon-face.jpg", alt: "\"Nostalgia Room\" — #afroart #iconart #compositing #graphicdesign #surrealism", subtitle: "Breana Taylor", note: "RIP Breana Taylor, tragically gunned down while safely in her home asleep" },
  { src: "/design/earth-cube-underwater-man.jpg", alt: "\"Nostalgia Room\" — #selfportrait #surrealism #graphicdesign #photography", subtitle: "Homebody", medium: "Photography, Digital Composite, Self-Work", note: "Surrealism edit from visit in Sint Maarten" },
  { src: "/design/fire-scarf-bust.jpg", alt: "\"Nostalgia Room\" — #selfportrait #graphicdesign #surrealism #aicoloring", subtitle: "Human Torch", medium: "Photography, Digital Composite, Self-Work", note: "A sunny day on Manhattan Beach" },
  { src: "/design/floral-halo-wave-portrait.jpg", alt: "\"Nostalgia Room\" — #selfportrait #graphicdesign #compositing #surrealism #photography", subtitle: "Nerd Surf", medium: "Photography, Digital Composite, Self-Work", note: "A sunny day over Manhattan Beach" },
  { src: "/design/flower-goddess-moon.jpg", alt: "\"Nostalgia Room\" — #commission #photography #graphicdesign #surrealism #compositing", subtitle: "Peachy Fruit", medium: "Photography, Digital Composite, Self-Work", note: "Peaches bearing fruit" },
  { src: "/design/four-by-the-tide.jpg", alt: "\"Stepford Side Chixx: Season 2\" — #photography #series #group #film #campaign #photocommission #field #beach #stepfordsidechixx", medium: "Photography, Campaign", note: "Season 2 photoshoot for Stepford Side Chixx marketing and promo;main cast" },
  { src: "/design/four-looks-banner.jpg", alt: "\"Multi-Hyphenate Man\" — #photography #editorial #compositing #studio #model #photocommission #portfolio #fashion", medium: "Photography", note: "Editorial shoot commission" },
  { src: "/design/garden-walk-cover.jpg", alt: "\"Garden Walk\" — #aiart #marketing #reelart", medium: "AI prompted art", note: "reel art; cover for reel video" },
  { src: "/design/gilded-statues-storm-scene.jpg", alt: "\"Nostalgia Room\" — #graphicdesign #compositing #surrealism", subtitle: "Carmen in the Veranda", medium: "Digital Composite, Self-Work", note: "Carmen in the veranda" },
  { src: "/design/hooded-guitarist.jpg", alt: "\"Guitar Slayer\" — #photography #music #studio #photocommission #musician #lightroom", note: "photoshoot with Justin \"Guitar Slayer\" Lyons; Dallas, TX" },
  { src: "/design/island-rainbow-rocket-woman.jpg", alt: "\"Nostalgia Room\" — #commission #graphicdesign #surrealism #compositing #afroart", subtitle: "Stefany on the Move", note: "Stefany is an LA girl on the move" },
  { src: "/design/its-always-somethin-poster.jpg", alt: "\"It's Always… Somethin'\" — #posterart #graphicdesign #compositing #series #coverart #commission #film", medium: "Digital Composite, Self-Work", note: "It's Always...Somethin is commission cover art for Series created project" },
  { src: "/design/jungle-chair-camera-legs-woman.jpg", alt: "\"Nostalgia Room\" — #commission #graphicdesign #surrealism #compositing photography", medium: "Photography, Digital Composite", note: "Commission for client creative comp card" },
  { src: "/design/jungle-neon-water-portrait.jpg", alt: "\"Nostalgia Room\" — #selfportrait #graphicdesign #surrealism #compositing #photography" },
  { src: "/design/jungle-x-portrait.jpg", alt: "#graphicdesign #iconart #surrealism #compositing #afroart #malcolmX" },
  { src: "/design/kobe-tribute-planet.jpg", alt: "Cross — #coverart #commission #surrealism #music #compositing #graphicdesign" },
  { src: "/design/leaf-seventeen.jpg", alt: "#commission #graphicdesign" },
  { src: "/design/loomieverse-clocks-jeep.jpg", alt: "\"LOOMIEVERSE\" cover art — #coverart #commission #graphicdesign #compositing #surrealism" },
  { src: "/design/loomieverse-collage.jpg", alt: "\"Loomieverse\" —\n#commission #coverart #graphicdesign #surrealism #music" },
  { src: "/design/loomis-butterfly-cover.jpg", alt: "\"Loomi$\" Presskit cover #commission #graphicdesign #compositing #coverart #presskit #music" },
  { src: "/design/melting-macaw.jpg", alt: "#graphicdesign #surrealism #compositing" },
  { src: "/design/midtown-student-living-flyer.jpg", alt: "\"Midtown Urban Student Living\" — #posters #graphicdesign #compositing #marketing #commission" },
  { src: "/design/mirokol-hummingbird-portrait.jpg", alt: "\"mirok·e·l\" cover art — #commission #coverart #graphicdesign #compositing #music" },
  { src: "/design/mosaic-village-family.jpg", alt: "#graphicdesign #compositing #afroart" },
  { src: "/design/neon-blood-couple.jpg", alt: "#commission #graphicdesign #compositing #surrealism" },
  { src: "/design/neon-outline-couple.jpg", alt: "#commission #graphicdesign #photography #compositing #afroart" },
  { src: "/design/neon-sunset-smoking.jpg", alt: "#graphicdesign #surrealism #compositing #iconart #gracejones" },
  { src: "/design/nightclub-crowd.jpg", alt: "Drake — #photography #event #club #field #celebrity #drake" },
  { src: "/design/nu-outcast-planet-cover.jpg", alt: "\"Nu Outcast\" cover art — #commission #coverart #music #compositing #graphicdesign" },
  { src: "/design/palm-leaf-sunset-portrait.jpg", alt: "#photography #graphicdesign #compositing #surrealism #campaign #afroart" },
  { src: "/design/panther-floral-portrait.jpg", alt: "#graphicdesign #iconart #afroart #compositing #chadwickboseman #blackandwhite" },
  { src: "/design/paradise-album-cover.jpg", alt: "\"Paradise\" — album cover for Jamal Moore featuring Kenyon Dixon #graphicdesign #commission #compositing #coverart #music" },
  { src: "/design/pedestal-of-life.jpg", alt: "\"Pedestal of Life\" — #commission #graphicdesign #surrealism #compositing #afroart #photography" },
  { src: "/design/phone-booth-neon-night.jpg", alt: "#graphicdesign #compositing" },
  { src: "/design/piano-stairway-car.jpg", alt: "#commission #Presskit #graphicdesign #compositing #surrealism #music #campaign" },
  { src: "/design/plant-jar-face.jpg", alt: "#selfportrait #photography #ailighting" },
  { src: "/design/roquet-double-exposure.jpg", alt: "\"Croquet\" — #graphicdesign #compositing #surrealism #campaign #photography #studio #campaign" },
  { src: "/design/shoreline-ensemble.jpg", alt: "\"Stepford Side Chixx: Season 2\" — #photography #afroart #campaign #photocommission #beach #field #group #series" },
  { src: "/design/smoke-butterfly-jeweled-portrait.jpg", alt: "#graphicdesign #iconart #afroart #aisubject #biggiesmalls #compositing" },
  { src: "/design/stage-performer-smoke.jpg", alt: "\"Future\" — #photography #livemusic #event #club #celebrity" },
  { src: "/design/sunset-suspenders-portrait.jpg", alt: "#photography #fashion #editorial #model #photocommission #field" },
  { src: "/design/swan-sunset.jpg", alt: "#graphicdesign #surrealism #compositing" },
  { src: "/design/three-heads-leaves.jpg", alt: "#commission #photography #graphicdesign #compositing #campaign #surrealism #afroart" },
  { src: "/design/toddler-green-armchair.jpg", alt: "#photography #field #childphotography #photocommission #staging" },
  { src: "/design/toddler-mirror-sky.jpg", alt: "#photography #field #childphotography #photocommission #staging" },
  { src: "/design/tree-head-chair-bw.jpg", alt: "#graphicdesign #compositing #blackandwhite" },
  { src: "/design/ufo-abduction-bw.jpg", alt: "#blackandwhite #surrealism #photography #design #compositing" },
  { src: "/design/underwater-boxer-storm.jpg", alt: "#graphicdesign #surrealism #iconart #compositing #afroart #muhammadali" },
  { src: "/design/underwater-leaf-koi-portrait.jpg", alt: "#selfportrait #graphicdesign #compositing #afroart #photography" },
  { src: "/design/vinyl-sofa-portrait.jpg", alt: "\"Nostalgic Grey\" — #blackandwhite #photography #lightroom #model #fashion #staging #editorial #photocommission", note: "Editorial shoot with male model" },
  { src: "/design/vinyl-sofa-reclined.jpg", alt: "#blackandwhite #photography #lightroom #model #fashion #staging #editorial #photocommission" },
  { src: "/design/zebra-border-wave-portrait.jpg", alt: "#selfportrait #photography #graphicdesign #surrealism #compositing" },
];

export function tagsOf(alt) {
  return (alt.match(/#[a-z0-9]+/gi) || []).map((t) => t.slice(1).toLowerCase());
}
